#ifndef INVENTORYMANAGEMENTAPPLICATION_IMGUI_CONTENT_WINDOW_H
#define INVENTORYMANAGEMENTAPPLICATION_IMGUI_CONTENT_WINDOW_H

#include "../ThirdParty/DearImgui/imgui.h"

namespace properties {
ImVec4 clear_color = ImVec4(0.45f, 0.55f, 0.60f, 1.00f);
}

#endif //INVENTORYMANAGEMENTAPPLICATION_IMGUI_CONTENT_WINDOW_H
